spring:
  application:
    name: dubbo-server-demo
dubbo:
  scan:
    base-packages: com.ylspringboot.dubbo.dubboserver.service
  protocol:
    port: 20880
    ##协议名称(dubbo,rmi,hessian,http,webservice,thrift,memcached,redis,rest)默认是dubbo
    name: dubbo
  registry:
    address: zookeeper://118.190.37.175:2181?timeout=30000
  application:
    name: dubbo-server-demo
server:
  port: 8081